FROM python:alpine3.7 
COPY . /Users/rohitshalgar/Documents/Flask/. 
WORKDIR /Users/rohitshalgar/Documents/Flask/. 
RUN pip install -r requirements.txt 
EXPOSE 5001 
ENTRYPOINT [ "python" ] 
CMD [ "Hello-world.py" ] 
